<dl>
    <div class="meta-group">
        <dt><?= $this->translate('Starting URL') ?></dt>
        <dd class="value"><?= $startUrl ? $this->escapeHtml($startUrl) : $this->translate('[none]') ?></dd>
    </div>
    <div class="meta-group">
        <dt><?= $this->translate('Embed mode') ?></dt>
        <dd class="value"><?= $this->translate($embedModes[$embedMode] ?? '[Site default]') ?></dd>
    </div>
</dl>
